name: Android CI

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.5
    - name: Grant execute permission for gradlew
      run: gradle wrapper && chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
